defmodule SpendLog.Repo.Migrations.AddSpendingDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:spending_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :amount, :decimal, null: false, precision: 12, scale: 2
      add :date, :date, null: false
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :category_id, :uuid, null: false
    end

    create table(:spending_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:spending_entries) do
      modify :category_id,
             references(:spending_categories,
               column: :id,
               name: "spending_entries_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:spending_categories) do
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:spending_categories, [:name],
             name: "spending_categories_unique_name_index"
           )
  end

  def down do
    drop_if_exists unique_index(:spending_categories, [:name],
                     name: "spending_categories_unique_name_index"
                   )

    alter table(:spending_categories) do
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop constraint(:spending_entries, "spending_entries_category_id_fkey")

    alter table(:spending_entries) do
      modify :category_id, :uuid
    end

    drop table(:spending_categories)

    drop table(:spending_entries)
  end
end
