defmodule SpendLog.Repo.Migrations.AddSpendingEntryDateIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:spending_entries, [:date])
  end

  def down do
    drop_if_exists index(:spending_entries, [:date])
  end
end
